name: AoC-badges
on:
  schedule: # run workflow based on schedule
    - cron: "30 5 1-25 12 *" # from the 1. December till 25. December every day at 5:06am (avoid load at full hours)

  workflow_dispatch: # allow to manually start the workflow

  push: # Run on push, be carefull with this setting as the workflow should not be triggered more than 4 times/hour

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # clones your repo

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2015 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202015%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2016 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202016%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2017 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202017%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2018 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202018%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2019 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202019%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2020 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202020%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2021 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202021%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2022 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202022%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
          year: 2023 # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202023%20⭐-)[0-9]+(?=-yellow)' # Regular expression that finds the content of the stars badge in your file.

      - uses: stefanzweifel/git-auto-commit-action@v4 # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md
